EURAUD = "EURAUD"
AUDEUR = "AUDEUR"
AUDUSD = "AUDUSD"
USDAUD = "USDAUD"

CASH_CURRENCY = "AUD" 

BUY = "BUY MORE"
SELL = "SELL"
STAY = "KEEP COOL AND STAY IN"

TREND_NO_CHANGE = "right"
TREND_UP = "up"
TREND_DOWN = "down"

NUMBER_VALUATIONS = 10

REFRESH_TIME = 3.minutes

CASH_ACCOUNT = "cash"
TRADING_ACCOUNT = "trading"

ORDER_TYPE_BUY ="BUY"
ORDER_TYPE_SELL ="SELL"

STARTING_BALANCE = 1000

LEADER_BOARD_LENGTH = 10