EURAUD = "EURAUD"
AUDEUR = "AUDEUR"
AUDUSD = "AUDUSD"
USDAUD = "USDAUD"

BUY = "BUY MORE"
SELL = "SELL"
STAY = "KEEP COOL AND STAY IN"

TREND_NO_CHANGE = "right"
TREND_UP = "up"
TREND_DOWN = "down"

NUMBER_VALUATIONS = 10
